#!/bin/bash

# Bootstrap the user customization of the linux environment so that permanent
# information is stored in {HOME}/julie.env and
# can be installed on any node with a simple git clone

# This also allows changing linux environment for shared accounts by running bootstrap after login
#
# dir structure
# linux_env
#   /bash
#       /.profile
#       /.bash_profile
#       /.bashrc
#   /vim
#       /.vimrc
#   /git


# git clone linux_env $HOME/$julie.env
# > bootstrap

# TODO: add support for a local directory to contain all the changing files
# such as shell history

USER_ENV_DIR=$(dirname "$(readlink -f "${BASH_SOURCE}")")
. ${USER_ENV_DIR}/env.conf


for source in ${USER_ENV_DIR}/dot_files/*
do
    target=${HOME}/.$(basename ${source})
    if [ -L ${target} ]
    then
        rm ${target}
    fi
    if [ -e ${target} ]
    then
	echo "ERROR: unable to create link ${target} because file exists"
    else
    	echo "Linking ${target} to ${source}"
    	ln -s ${source} ${target}
    fi
done

# directory links
for dir in bin
do
    target=${HOME}/${dir}
    source=${USER_ENV_DIR}/${dir}
    if [ -L ${target} ]
    then
        rm ${target}
    fi
    if [ -e ${target} ]
    then
	echo "ERROR: unable to create link ${target} because file exists"
    else
    	echo "Linking ${target} to ${source}"
    	ln -s ${source} ${target}
    fi
done

# TODO:
# dircolors

